FROM debian:trixie-slim@sha256:a347fd7510ee31a84387619a492ad6c8eb0af2f2682b916ff3e643eb076f925a
# ntp to keep correct time
# curl to enable compose healthchecks
RUN apt-get update -qq \
    && apt-get upgrade -y -qq \
    && apt-get install -y -qq ca-certificates curl gnupg procps strace gdb vim jq tree \
    && rm -rf /var/lib/apt/lists/*

# Add NodeSource repository with GPG verification
RUN mkdir -p /usr/share/keyrings && \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor --yes -o /usr/share/keyrings/nodesource.gpg

COPY .envrc ./bin/.envrc
COPY static/contracts/simple-merkle-tree /test-static/simple-merkle-tree

ENV TOOLKIT_JS_PATH="/toolkit-js"
ENV MIDNIGHT_LEDGER_TEST_STATIC_DIR=/test-static
ENV MIDNIGHT_PP=/.cache/midnight/zk-params
ENV MN_FETCH_CACHE=redb:/.cache/fetch/toolkit.db

# Get node version for the image tag
COPY node/Cargo.toml /node/
RUN cat /node/Cargo.toml | grep -m 1 version | sed 's/version *= *"\([^\"]*\)".*/\1/' > node_version && \
  rm -rf /node
COPY util/toolkit/bin/entrypoint.sh /entrypoint.sh

RUN useradd -u 10001 -d /nonexistent -s /usr/sbin/nologin -M -U -c "" appuser && passwd -l appuser
USER appuser
ENTRYPOINT ["/entrypoint.sh"]
