chain = "res/devnet/chain-spec.json"
base_path = "node/chain"

chainspec_name = "Midnight devnet"
chainspec_id = "midnight_devnet"
chainspec_genesis_state = "res/genesis/genesis_state_devnet.mn"
chainspec_genesis_block = "res/genesis/genesis_block_devnet.mn"
chainspec_chain_type = "live"
chainspec_pc_chain_config = "res/devnet/pc-chain-config.json"
chainspec_cnight_genesis = "res/devnet/cnight-genesis.json"
chainspec_federated_authority_config = "res/devnet/federated-authority-config.json"
chainspec_system_parameters_config = "res/devnet/system-parameters-config.json"
