chain = "res/govnet/chain-spec.json"
base_path = "node/chain"

chainspec_name = "Midnight GovNet"
chainspec_id = "midnight_govnet"
chainspec_genesis_state = "res/genesis/genesis_state_govnet.mn"
chainspec_genesis_block = "res/genesis/genesis_block_govnet.mn"
chainspec_chain_type = "live"
chainspec_pc_chain_config = "res/govnet/pc-chain-config.json"
chainspec_cnight_genesis = "res/govnet/cnight-genesis.json"
chainspec_federated_authority_config = "res/govnet/federated-authority-config.json"
chainspec_system_parameters_config = "res/govnet/system-parameters-config.json"
