chain = "res/node-dev-01/chain-spec-raw.json"
base_path = "node/chain"

chainspec_name = "Midnight NodeDev01"
chainspec_id = "midnight_node-dev-01"
chainspec_genesis_state = "res/genesis/genesis_state_node-dev-01.mn"
chainspec_genesis_block = "res/genesis/genesis_block_node-dev-01.mn"
chainspec_chain_type = "live"
chainspec_pc_chain_config = "res/node-dev-01/pc-chain-config.json"
chainspec_cnight_genesis = "res/node-dev-01/cnight-config.json"
chainspec_ics_config = "res/node-dev-01/ics-config.json"
chainspec_federated_authority_config = "res/node-dev-01/federated-authority-config.json"
chainspec_system_parameters_config = "res/node-dev-01/system-parameters-config.json"
chainspec_permissioned_candidates_config = "res/node-dev-01/permissioned-candidates-config.json"
chainspec_registered_candidates_addresses = "res/node-dev-01/registered-candidates-addresses.json"
