chain = "res/preview/chain-spec-raw.json"
base_path = "node/chain"

chainspec_name = "Midnight Preview"
chainspec_id = "midnight_preview"
chainspec_genesis_state = "res/genesis/genesis_state_preview.mn"
chainspec_genesis_block = "res/genesis/genesis_block_preview.mn"
chainspec_chain_type = "live"
chainspec_pc_chain_config = "res/preview/pc-chain-config.json"
chainspec_cnight_genesis = "res/preview/cnight-config.json"
chainspec_ics_config = "res/preview/ics-config.json"
chainspec_federated_authority_config = "res/preview/federated-authority-config.json"
chainspec_system_parameters_config = "res/preview/system-parameters-config.json"
chainspec_permissioned_candidates_config = "res/preview/permissioned-candidates-config.json"
chainspec_registered_candidates_addresses = "res/preview/registered-candidates-addresses.json"
