name: +check (format + lint)

on:
  merge_group:
  pull_request:
    branches: ["**"]
    paths-ignore:
      - "changes/**"
  push:
    branches: ["main"]
concurrency:
  group: ${{ github.event_name == 'pull_request' && format('{0}-{1}', github.workflow, github.head_ref) || github.run_id }}
  cancel-in-progress: true
jobs:
  run:
    name: Fomatting and Linting
    runs-on: ubuntu-latest-16-core-x64
    env:
      FORCE_COLOR: 1
    steps:
      - uses: EarthBuild/actions-setup@cae2d9ab68894d8402751fe42e07c7cca0272f7f
        with:
          version: v0.8.16
          github-token: ${{ github.token }}
          use-cache: false

      - name: Checkout node repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1

      - name: Merge Conflict Finder
        uses: olivernybroe/action-conflict-finder@78f7add155e0bf97e9c71cb0383ef5691f72868c # v4.0

      - name: Run build
        run: |
          . ./.envrc && earthly --ci +check
